import * as T from './base-assets/vendor/three.module.min.js';
import {GLTFLoader} from './base-assets/vendor/GLTFLoader.js';
import {clone} from './base-assets/vendor/SkeletonUtils.js';
import {meshFor,partEnvelope} from './base-logic.js';
export function createBaseScene(canvas,buildings,visuals,report){
 const renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor('#081e2b');
 const scene=new T.Scene(),camera=new T.OrthographicCamera(-10,10,10,-10,.01,4000),target=new T.Vector3(),placed=new T.Group(),loader=new GLTFLoader(),textureLoader=new T.TextureLoader(),models=new Map(),textures=new Map(),instances=new Map(),ownedMaterials=new Set();
 scene.add(placed,new T.HemisphereLight(0xccefff,0x47533a,2.5));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(20,40,30);scene.add(sun);const fill=new T.DirectionalLight(0x88beff,1.3);fill.position.set(-25,15,-20);scene.add(fill);
 const grid=new T.GridHelper(160,160,0x417485,0x244b5c);grid.material.transparent=true;grid.material.opacity=.5;scene.add(grid);
 const box=new T.Box3Helper(new T.Box3(),0x67e0c6);box.visible=false;scene.add(box);
 let scale=24,azimuth=Math.PI/4,polar=.65,view='isometric',disposed=false,lastParts=[],selected=null,plane=0,pending=0,failures=new Set();
 const native=([x,y,z])=>new T.Vector3(x,z,-y);
 function render(){if(disposed)return;const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.left=-w/(2*scale);camera.right=w/(2*scale);camera.top=h/(2*scale);camera.bottom=-h/(2*scale);camera.updateProjectionMatrix();const dir=new T.Vector3(Math.sin(polar)*Math.sin(azimuth),Math.cos(polar),Math.sin(polar)*Math.cos(azimuth));camera.position.copy(target).addScaledVector(dir,500);camera.up.set(0,1,0);if(polar<.001)camera.up.set(0,0,-1);camera.lookAt(target);camera.updateMatrixWorld();grid.position.y=plane-.012;const obj=instances.get(selected)?.object;box.visible=!!obj;if(obj)box.box.setFromObject(obj);renderer.render(scene,camera);}
 function texture(path,color=false){if(!textures.has(path)){const tex=textureLoader.load('./base-assets/'+path,render,undefined,()=>{report('Some textures could not load. Retry this page to restore their appearance.');});tex.flipY=false;tex.wrapS=tex.wrapT=T.RepeatWrapping;if(color)tex.colorSpace=T.SRGBColorSpace;textures.set(path,tex);}return textures.get(path);}
 function override(binding){const m=new T.MeshStandardMaterial({roughness:binding.roughness,metalness:0,side:T.DoubleSide,transparent:[2,3,4,5].includes(binding.blend),opacity:[2,3,4,5].includes(binding.blend)?.6:1,alphaTest:binding.blend===1?.33:0});if(binding.color)m.map=texture(binding.color,true);if(binding.normal)m.normalMap=texture(binding.normal);ownedMaterials.add(m);return m;}
 function model(path){if(!models.has(path)){pending++;report('Loading game models…');models.set(path,loader.loadAsync('./'+path).then(g=>g.scene).catch(()=>{failures.add(path);return null;}).finally(()=>{pending--;if(!disposed)report(pending?'Loading game models…':failures.size?`${failures.size} model assets unavailable; outlined envelopes shown.`:'Game models loaded.');}));}return models.get(path);}
 function placeholder(p){const mesh=meshFor({...p,x:0,y:0,z:0,rotation:0},buildings.get(p.building)),g=new T.BufferGeometry(),positions=[];for(const face of mesh.faces)for(let i=1;i<face.length-1;i++)for(const j of[face[0],face[i],face[i+1]])positions.push(...native(mesh.vertices[j]).toArray());g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.computeVertexNormals();const m=new T.MeshStandardMaterial({color:0x6a9fba,transparent:true,opacity:.28,wireframe:true});ownedMaterials.add(m);return new T.Mesh(g,m);}
 function orient(obj,p){obj.position.set(p.x,p.z,-p.y);obj.rotation.y=p.rotation*Math.PI/180;}
 function release(entry){entry.placeholder?.geometry.dispose();entry.placeholder?.material.dispose();if(entry.placeholder)ownedMaterials.delete(entry.placeholder.material);for(const m of entry.materials||[]){m.dispose();ownedMaterials.delete(m);}}
 function update(parts,id){selected=id;lastParts=parts;const ids=new Set(parts.map(p=>p.id));for(const[id,v]of instances)if(!ids.has(id)){placed.remove(v.object);release(v);instances.delete(id);}
  for(const p of parts){const signature=JSON.stringify([p.building,p.size||null]);let entry=instances.get(p.id);if(!entry||entry.signature!==signature){if(entry){placed.remove(entry.object);release(entry);}const object=new T.Group(),fallback=placeholder(p);object.add(fallback);entry={object,signature,placeholder:fallback,materials:[]};instances.set(p.id,entry);placed.add(object);const e=entry,v=visuals.buildings[p.building];if(v?.parts.length)Promise.all(v.parts.map(async c=>{const source=await model(c.model);if(!source||disposed||instances.get(p.id)!==e)return null;const obj=clone(source);const own=b=>{const m=override(b);e.materials.push(m);return m;};if(c.overrides?.some(Boolean))obj.traverse(n=>{if(n.isMesh){if(Array.isArray(n.material))n.material=n.material.map((m,i)=>c.overrides[i]?own(c.overrides[i]):m);else if(c.overrides[0])n.material=own(c.overrides[0]);}});obj.applyMatrix4(new T.Matrix4().fromArray(c.matrix));return obj;})).then(objects=>{if(disposed||instances.get(p.id)!==e)return;const good=objects.filter(Boolean);if(!good.length)return;e.placeholder.geometry.dispose();e.placeholder.material.dispose();ownedMaterials.delete(e.placeholder.material);e.placeholder=null;e.object.clear();for(const o of good)e.object.add(o);if(p.size){const env=buildings.get(p.building)?.envelope;if(env)e.object.scale.set(p.size[0]/(env.max[0]-env.min[0]),p.size[2]/(env.max[2]-env.min[2]),p.size[1]/(env.max[1]-env.min[1]));}render();});}
   orient(entry.object,p);entry.object.userData.partId=p.id;
  }render();
 }
 const ghost=new T.Group();scene.add(ghost);let ghostKey=null,ghostSerial=0,ghostMaterials=[];
 function preview(p){if(!p){ghost.visible=false;render();return;}ghost.visible=true;orient(ghost,p);if(ghostKey!==p.building){ghostKey=p.building;const serial=++ghostSerial;ghostMaterials.forEach(m=>{m.dispose();ownedMaterials.delete(m);});ghostMaterials=[];ghost.clear();const v=visuals.buildings[p.building];if(v?.parts.length)Promise.all(v.parts.map(async c=>{const source=await model(c.model);if(!source||disposed||serial!==ghostSerial)return null;const o=clone(source);o.applyMatrix4(new T.Matrix4().fromArray(c.matrix));return o;})).then(objects=>{if(disposed||serial!==ghostSerial)return;for(const o of objects.filter(Boolean)){o.traverse(n=>{if(n.isMesh){const tint=m=>{const c=m.clone();c.transparent=true;c.opacity=.4;c.depthWrite=false;c.color.multiply(new T.Color(0x78ffe2));ghostMaterials.push(c);ownedMaterials.add(c);return c;};n.material=Array.isArray(n.material)?n.material.map(tint):tint(n.material);}});ghost.add(o);}render();});}render();}
 const ray=new T.Raycaster();function cast(point){ray.setFromCamera(new T.Vector2(point[0]/canvas.clientWidth*2-1,1-point[1]/canvas.clientHeight*2),camera);}
 function world(point,height=plane){cast(point);let normal=new T.Vector3(0,1,0),constant=-height;if(view==='front'||view==='back'){normal.set(0,0,1);constant=-target.z;}if(view==='left'||view==='right'){normal.set(1,0,0);constant=-target.x;}const p=ray.ray.intersectPlane(new T.Plane(normal,constant),new T.Vector3());return p?{x:p.x,y:-p.z,z:p.y}:{x:target.x,y:-target.z,z:height};}
 function pick(point){cast(point);const hit=ray.intersectObjects(placed.children,true)[0];let obj=hit?.object;while(obj&&!obj.userData.partId)obj=obj.parent;return obj?.userData.partId||null;}
 function pan(dx,dy){camera.updateMatrixWorld();const right=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,1);target.addScaledVector(right,-dx/scale).addScaledVector(up,dy/scale);render();}
 function orbit(dx,dy){view='orbit';azimuth-=dx*.008;polar=Math.max(.05,Math.min(Math.PI-.05,polar+dy*.008));render();}
 function setView(v){view=v;const presets={top:[0,0],front:[0,Math.PI/2],back:[Math.PI,Math.PI/2],left:[-Math.PI/2,Math.PI/2],right:[Math.PI/2,Math.PI/2],isometric:[Math.PI/4,.65]};[azimuth,polar]=presets[v]||presets.isometric;render();}
 function fit(){const b=new T.Box3();for(const p of lastParts){const obj=instances.get(p.id)?.object;if(obj)b.expandByObject(obj);}if(b.isEmpty()){target.set(0,0,0);scale=24;}else{b.getCenter(target);const size=b.getSize(new T.Vector3()),extent=Math.max(size.x,size.y,size.z,4);scale=Math.max(2,Math.min(80,Math.min(canvas.clientWidth,canvas.clientHeight)*.65/extent));}render();}
 const observer=new ResizeObserver(render);observer.observe(canvas);render();
 return{update,preview,world,pick,pan,orbit,setView,fit,zoom:f=>{scale=Math.min(200,Math.max(1,scale*f));render();},setPlane:z=>{target.y+=z-plane;plane=z;render();},render,dispose(){disposed=true;observer.disconnect();const gs=new Set(),ms=new Set(ownedMaterials),ts=new Set(textures.values());scene.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){ms.add(m);for(const v of Object.values(m))if(v?.isTexture)ts.add(v);}});for(const promise of models.values())promise.then(obj=>obj?.traverse(o=>{o.geometry?.dispose();for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}));gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());renderer.dispose();}};
}
