import {newBlueprint,readBlueprints,writeBlueprints,parseBlueprint,exportBlueprint,mergeBlueprints,baseStorageKey} from './base-storage.js';
import {project,unproject,snap,rotate,defaultEnvelope,partEnvelope,meshFor,insidePolygon,constructionBill,rawBill,technologyRequirements} from './base-logic.js';
import {readProfile} from './player-tools/storage.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>Number(n.toFixed(2)).toLocaleString();
const copy=x=>structuredClone(x);
const groupNames={Barieer:'Gates & defensive walls',Clean:'Advanced structures',Deforest_Mining:'Logging & mining',EfficiencEnhancement:'Work improvements',FeedBox:'Feed boxes',FishingPond:'Fishing ponds',Interception:'Defenses',PalCaptureItem:'Sphere crafting',PalManagement:'Pal management',PalOther:'Pal facilities',PalTraining:'Training & breeding',Product_Repair:'Crafting & repair',Refine:'Furnaces',StorageFurniture:'Storage furniture',WallDecoration:'Wall decorations',WallHanging:'Wall lights',Milling_Crusher:'Mills & crushers',JapaneseStyle:'Japanese style'};
const groupName=id=>groupNames[id]||id.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ');
const categoryNames={Foundation:'Building parts',Product:'Crafting stations',Pal:'Pal care',Infrastructure:'Base facilities',Light:'Lighting',Food:'Farming & food',Defense:'Defenses'};
const categoryName=id=>categoryNames[id]||groupName(id);
const download=(name,blob)=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
let cached;
export async function renderBaseBuilder(content){
 const initialHash=location.hash;content.innerHTML='<p>Opening the blueprint editor…</p>';
 if(!cached){const r=await fetch('./base-data.json?v=base-1');if(!r.ok)throw Error('Building data could not load.');cached=await r.json();}
 if(location.hash!==initialHash)return;
 const data=cached,buildings=new Map(data.buildings.map(x=>[x.id,x]));
 const itemData=await fetch('./wiki-data.json?v=recovery-2').then(r=>{if(!r.ok)throw Error('Item names could not load.');return r.json();});if(location.hash!==initialHash)return;
 const items=new Map(itemData.items.map(x=>[x.id,x]));
 let plans=readBlueprints(localStorage);if(!plans.length)plans=[newBlueprint()];
 const selectionKey='palwaypoint-blueprint-selection-v1';
 let current=localStorage.getItem(selectionKey);if(!plans.some(p=>p.id===current))current=plans[0].id;
 let selected=null,brush='Wooden_foundation',mode='place',view='top',plane=0,step=.5,rotation=0,labels=false,isolated=false,undo=[],redo=[],camera={scale:24,x:0,y:0},polygons=[],drag=null,hover=null;
 let latest=localStorage.getItem(baseStorageKey);
 const controller=new AbortController(),signal=controller.signal;
 const plan=()=>plans.find(p=>p.id===current);
 content.innerHTML=`<div class="base-builder"><div class="base-manager"><label>Saved blueprint<select id="base-plans"></select></label><label>Blueprint name<input id="base-name" maxlength="100"></label><button id="base-new">New base</button><button id="base-copy">Copy base</button><button id="base-remove" class="base-danger">Delete base</button><p class="base-help">Plans stay in this browser. Export a blueprint or use <a href="#backup">Back up &amp; restore</a> to keep a copy.</p></div>
 <div class="base-banner">Place parts on a grid and inspect the same design from every side. Sizes use game mesh bounds where available; shapes are simplified. Terrain, snapping, structural support and Pal pathfinding are not simulated.</div>
 <div class="base-workspace"><details class="base-library base-panel" open><summary>Building parts</summary><div class="base-catalog-tools"><label>Find a part<input id="base-search" type="search" placeholder="Foundation, chest, station…"></label><label>Category<select id="base-category"><option value="">All categories</option>${[...new Set(data.buildings.map(b=>b.category))].map(c=>`<option value="${esc(c)}">${esc(categoryName(c))}</option>`).join('')}</select></label><label>Building set<select id="base-group"><option value="">All sets</option>${[...new Set(data.buildings.map(b=>b.group))].sort().map(c=>`<option value="${esc(c)}">${esc(groupName(c))}</option>`).join('')}</select></label></div><p id="base-catalog-count" class="base-library-count"></p><div id="base-library" class="base-part-list"></div></details>
 <div class="base-editor base-panel"><div class="base-toolbar" id="base-views" aria-label="Blueprint view">${['top','front','back','left','right','isometric'].map(v=>`<button data-view="${v}" aria-pressed="${v==='top'}">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div>
 <div class="base-place-controls"><label>Placement height (m)<input id="base-plane" type="number" value="0" min="-500" max="500" step=".5"></label><label>Grid step<select id="base-step"><option value=".25">0.25 m</option><option value=".5" selected>0.5 m</option><option value="1">1 m</option><option value="2">2 m</option><option value="4">4 m</option></select></label><label>Place rotation<select id="base-rotation">${[0,45,90,135,180,225,270,315].map(n=>`<option value="${n}">${n}°</option>`).join('')}</select></label><label class="base-toggle"><input type="checkbox" id="base-isolate">Only this height</label><label class="base-toggle"><input type="checkbox" id="base-labels">Labels</label></div>
 <div class="base-actions" id="base-modes"><button data-mode="place" aria-pressed="true">Place</button><button data-mode="select" aria-pressed="false">Select / move</button><button data-mode="pan" aria-pressed="false">Pan</button><button id="base-add">Add at center</button><button id="base-undo" disabled>Undo</button><button id="base-redo" disabled>Redo</button></div>
 <div class="base-canvas-wrap"><canvas id="base-canvas" class="base-canvas" tabindex="0" aria-label="Base blueprint. Choose a part and click to place it. Use the placed parts list and position fields for keyboard editing."></canvas><span id="base-view-label" class="base-view-label"></span></div>
 <div class="base-toolbar base-view-tools"><span class="base-render-count" id="base-part-count"></span><div class="base-toolbar"><button id="base-zoom-out" aria-label="Zoom out">−</button><button id="base-fit">Fit design</button><button id="base-zoom-in" aria-label="Zoom in">+</button></div></div>
 <p id="base-brush" class="base-editor-status"></p><p class="base-help">Tap to place; use Select / move to drag a part. Drag in Pan mode to move the view. Side views place at the center depth; edit X/Y/Z for exact positions. Dimensions and coordinates are in meters.</p>
 <details class="base-help"><summary>Controls &amp; geometry</summary><p>Mouse wheel zooms. In Select / move, R rotates 90°, Delete removes, Ctrl/Cmd+Z undoes and Ctrl/Cmd+Shift+Z redoes. Top shows X/Y, front/back show X/Z, left/right show Y/Z. The height filter uses each part’s placement anchor, not its full vertical span. Z is the native placement pivot: foundations extend below it. A mesh envelope includes decorative overhangs and may differ from collision or usable floor size. Parts with incomplete inherited meshes or no mesh use clearly labeled partial or estimated sizes. Game snapping, overlap, support and build-area rules are not enforced.</p></details>
 <div id="base-selection" class="base-selection"></div><details class="base-help"><summary>Placed parts</summary><div id="base-pieces" class="base-piece-list"></div></details>
 <label class="base-notes">Design notes<textarea id="base-notes" rows="2" maxlength="4000" placeholder="Floors, access routes, planned work areas…"></textarea></label>
 <div class="base-actions"><button id="base-export">Export blueprint</button><button id="base-image">Export view PNG</button><button id="base-print">Print blueprint</button></div><label class="base-import base-help">Import blueprint JSON<input type="file" accept=".json,application/json" id="base-import"></label><p id="base-status" role="status"></p></div></div>
 <div id="base-bill" class="base-bill"></div></div>`;
 const root=content.querySelector('.base-builder'),q=s=>root.querySelector(s),canvas=q('#base-canvas'),ctx=canvas.getContext('2d');
 const status=s=>{q('#base-status').textContent=s;};
 const on=(s,event,handler)=>q(s).addEventListener(event,handler,{signal});
 const itemLink=id=>`<a href="#item/${encodeURIComponent(id)}">${esc(items.get(id)?.name||id)}</a>`;
 const visible=()=>plan().parts.filter(p=>!isolated||Math.abs(p.z-plane)<.001);
 function saveMutation(fn,message='Blueprint saved on this browser.'){
  const before=copy(plans),oldCurrent=current;
  try{if(localStorage.getItem(baseStorageKey)!==latest)throw Error('Blueprints changed in another tab. Reopen this page before editing.');fn();plans=writeBlueprints(localStorage,plans);latest=localStorage.getItem(baseStorageKey);undo.push({plans:before,current:oldCurrent});if(undo.length>60)undo.shift();redo=[];update();status(message);}
  catch(e){plans=before;current=oldCurrent;update();status(e.message);}
 }
 function history(from,to){if(!from.length)return;const state=from.at(-1),previous=copy(plans),old=current;try{if(localStorage.getItem(baseStorageKey)!==latest)throw Error('Blueprints changed in another tab. Reopen this page.');writeBlueprints(localStorage,state.plans);latest=localStorage.getItem(baseStorageKey);from.pop();to.push({plans:previous,current:old});plans=copy(state.plans);current=state.current;if(!plan().parts.some(p=>p.id===selected))selected=null;update();status('Blueprint saved.');}catch(e){status(e.message);}}
 function library(){const query=q('#base-search').value.trim().toLowerCase(),category=q('#base-category').value,group=q('#base-group').value;const found=[...data.buildings].sort((a,b)=>(a.category==='Foundation'?0:1)-(b.category==='Foundation'?0:1)).filter(b=>(!query||`${b.name} ${b.id}`.toLowerCase().includes(query))&&(!category||b.category===category)&&(!group||b.group===group));q('#base-catalog-count').textContent=`${found.length} / ${data.buildings.length} parts`;q('#base-library').innerHTML=found.map(b=>`<button data-brush="${esc(b.id)}" aria-pressed="${brush===b.id}"><span class="base-part-symbol" style="color:${color(b)}" aria-hidden="true"></span><span><strong>${esc(b.name)}</strong><small>${esc(groupName(b.group))}${b.schematic?' · schematic':''}${!b.envelope?' · estimated size':''}</small></span></button>`).join('')||'<p>No matching parts.</p>';}
 function color(b){if(!b)return '#bf7694';const id=b.id.toLowerCase();if(id.includes('wood'))return '#ae8659';if(id.includes('glass'))return '#65baa9';if(id.includes('stone'))return '#9babb6';if(id.includes('metal')||id.includes('iron'))return '#90a9c8';if(b.category==='Foundation')return '#93a3cb';if(b.category==='Furniture')return '#a899c7';if(b.group==='Chest'||b.group==='StorageFurniture')return '#c3a266';return '#63afbd';}
 function screen(v){const p=project(v,view);return [canvas.clientWidth/2+camera.x+p[0]*camera.scale,canvas.clientHeight/2+camera.y+p[1]*camera.scale,p[2]];}
 function world(point,anchor={x:0,y:0}){return unproject([(point[0]-canvas.clientWidth/2-camera.x)/camera.scale,(point[1]-canvas.clientHeight/2-camera.y)/camera.scale],view,plane,anchor);}
 function draw(){
  const width=canvas.clientWidth,height=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(!width||!height)return;
  canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#081e2b';ctx.fillRect(0,0,width,height);polygons=[];
  const isTop=view==='top'||view==='isometric',span=80;ctx.lineWidth=1;
  const line=(a,b,shade)=>{const pa=screen(a),pb=screen(b);ctx.strokeStyle=shade;ctx.beginPath();ctx.moveTo(pa[0],pa[1]);ctx.lineTo(pb[0],pb[1]);ctx.stroke();};
  for(let i=-span;i<=span;i+=step){const major=Math.abs(i%4)<.001;const shade=i===0?'#417485':major?'#244b5c':'#163344';if(isTop){line([i,-span,plane],[i,span,plane],shade);line([-span,i,plane],[span,i,plane],shade);}else if(view==='front'||view==='back'){line([i,0,-span],[i,0,span],shade);line([-span,0,i],[span,0,i],shade);}else{line([0,i,-span],[0,i,span],shade);line([0,-span,i],[0,span,i],shade);}}
  const faces=[];for(const p of visible()){const b=buildings.get(p.building),mesh=meshFor(p,b),vertices=mesh.vertices.map(screen);for(let i=0;i<mesh.faces.length;i++){const face=mesh.faces[i],poly=face.map(j=>vertices[j]);const area=poly.reduce((n,v,j)=>n+v[0]*poly[(j+1)%poly.length][1]-poly[(j+1)%poly.length][0]*v[1],0);if(Math.abs(area)<.1)continue;faces.push({part:p,poly,depth:poly.reduce((n,v)=>n+v[2],0)/poly.length,color:color(b),i});}}
  faces.sort((a,b)=>a.depth-b.depth);for(const f of faces){ctx.beginPath();f.poly.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fillStyle=f.color;ctx.globalAlpha=f.part.id===selected?.9:.68;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=f.part.id===selected?'#d3fff0':'#0a2433';ctx.lineWidth=f.part.id===selected?2:1;ctx.stroke();polygons.push({id:f.part.id,poly:f.poly});}
  if(labels||selected)for(const p of visible().filter(p=>labels||p.id===selected)){const e=partEnvelope(p,buildings.get(p.building)),pos=screen([p.x,p.y,p.z+e.max[2]]),name=buildings.get(p.building)?.name||p.building;ctx.font='11px system-ui';ctx.textAlign='center';const w=ctx.measureText(name).width;ctx.fillStyle='#071b2cde';ctx.fillRect(pos[0]-w/2-4,pos[1]-18,w+8,17);ctx.fillStyle='#e5f9f2';ctx.fillText(name,pos[0],pos[1]-6);}
  if(hover&&mode==='place'){const p=world(hover),s=screen([snap(p.x,step),snap(p.y,step),view==='top'||view==='isometric'?plane:snap(p.z,step)]);ctx.strokeStyle='#67e0c6';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(s[0]-8,s[1]);ctx.lineTo(s[0]+8,s[1]);ctx.moveTo(s[0],s[1]-8);ctx.lineTo(s[0],s[1]+8);ctx.stroke();}
  q('#base-view-label').textContent=`${view[0].toUpperCase()+view.slice(1)} · ${step} m grid · Z ${plane} m`;
 }
 function fit(){const vertices=visible().flatMap(p=>meshFor(p,buildings.get(p.building)).vertices.map(v=>project(v,view)));if(!vertices.length){camera={scale:24,x:0,y:0};draw();return;}const min=[0,1].map(i=>Math.min(...vertices.map(p=>p[i]))),max=[0,1].map(i=>Math.max(...vertices.map(p=>p[i])));camera.scale=Math.min(100,Math.max(2,Math.min((canvas.clientWidth-70)/Math.max(max[0]-min[0],4),(canvas.clientHeight-70)/Math.max(max[1]-min[1],4))));camera.x=-(min[0]+max[0])/2*camera.scale;camera.y=-(min[1]+max[1])/2*camera.scale;draw();}
 function selection(){const p=plan().parts.find(x=>x.id===selected);if(!p){q('#base-selection').innerHTML='<p class="base-help">Select a placed part to edit its position, rotation and size.</p>';return;}const b=buildings.get(p.building),e=partEnvelope(p,b),size=e.max.map((n,i)=>n-e.min[i]);q('#base-selection').innerHTML=`<h3>${esc(b?.name||p.building)}</h3><p class="base-help">${p.size?'Custom size':!b?.envelope?'Estimated size':b.envelope.quality==='partial-mesh-envelope'?'Partial mesh envelope':'Game mesh envelope'} · simplified shape</p><div class="base-edit-fields">${['x','y','z','rotation'].map(k=>`<label>${k==='rotation'?'Rotation (°)':k.toUpperCase()+' (m)'}<input data-part-field="${k}" type="number" min="${k==='rotation'?0:-500}" max="${k==='rotation'?359.99:500}" step="any" value="${p[k]}"></label>`).join('')}${['Width (m)','Depth (m)','Height (m)'].map((k,i)=>`<label>${k}<input data-size-field="${i}" type="number" min=".01" max="100" step="any" value="${+size[i].toFixed(4)}"></label>`).join('')}</div><div class="base-actions"><button id="base-apply-position">Apply position</button><button id="base-apply-size">Apply size</button><button id="base-turn">Rotate 90°</button><button id="base-duplicate">Duplicate part</button><button id="base-size-reset">Reset size</button><button id="base-delete" class="base-danger">Remove part</button></div>${b?.description?`<p class="base-help">${esc(b.description)}</p>`:''}`;}
 function bill(){
  const bill=constructionBill(plan(),data),raw=rawBill(bill.materials,data.itemRecipes),required=technologyRequirements(bill.techs,data.technologies);let profile=null;try{profile=readProfile(localStorage);}catch{}
  const learned=new Set((profile?.progress?.technologies||[]).map(x=>x.toLowerCase())),owned=new Map();for(const stack of profile?.inventory||[])owned.set(stack.id,(owned.get(stack.id)||0)+stack.count);
  const mats=(map,compare=false)=>`<div class="base-table-scroll"><table><thead><tr><th>Material</th><th>Required</th>${compare?'<th>Carried</th><th>Missing</th>':''}</tr></thead><tbody>${[...map].sort((a,b)=>(items.get(a[0])?.name||a[0]).localeCompare(items.get(b[0])?.name||b[0])).map(([id,n])=>`<tr><td>${itemLink(id)}</td><td>${number(n)}</td>${compare?`<td>${number(owned.get(id)||0)}</td><td>${number(Math.max(0,n-(owned.get(id)||0)))}</td>`:''}</tr>`).join('')||'<tr><td colspan="4">Add a building part to start your materials list.</td></tr>'}</tbody></table></div>`;
  const compare=profile?.source==='local-world'&&Array.isArray(profile.inventory);
  const limits=[...bill.counts].filter(([id,n])=>buildings.get(id).limits.maxPerBase>0&&n>buildings.get(id).limits.maxPerBase);
  const unknownUnlocks=[...bill.counts].filter(([id])=>!buildings.get(id).technologies.length&&!buildings.get(id).schematic);
  const newTech=required.ids.filter(id=>!learned.has(id.toLowerCase())),points=newTech.reduce((r,id)=>{const t=data.technologies[id];r[t.ancient?'ancient':'normal']+=t.cost;return r;},{normal:0,ancient:0});
  q('#base-bill').innerHTML=`<section class="base-panel"><h2>Construction shopping list</h2><p class="base-help">${bill.counts.size} kinds of building · ${plan().parts.length} placed parts. Recipes are read from the installed game tables.</p>${mats(bill.materials,compare)}${compare?'<p class="base-help">Carried items are from your last local-world import. Base storage and already-built parts are not counted. Import a fresh save to update these amounts.</p>':'<p class="base-help">Import your own local world to compare with carried inventory. Server character files do not include it.</p>'}<details class="base-help"><summary>Raw materials if crafting everything</summary><p>Expands the recorded recipes, including intermediate materials. Each required batch is rounded up. This is an alternative list; do not add it to the construction list. Loot, purchases, alternate recipes and production settings can change what you need.</p>${mats(raw.materials)}${raw.issues.length?`<p class="base-alert">Recipe loops could not be expanded: ${raw.issues.map(itemLink).join(', ')}.</p>`:''}</details><h3>Building counts</h3><div class="base-table-scroll"><table><tbody>${[...bill.counts].map(([id,n])=>`<tr><td>${esc(buildings.get(id).name)}</td><td>×${n}</td></tr>`).join('')}</tbody></table></div>${limits.length?`<p class="base-alert">Recorded base limits exceeded: ${limits.map(([id])=>`${esc(buildings.get(id).name)} (max ${buildings.get(id).limits.maxPerBase})`).join(', ')}.</p>`:''}${bill.unknown.length?`<p class="base-alert">No recipe found for ${bill.unknown.map(esc).join(', ')}. These imported parts are retained but excluded from costs.</p>`:''}</section>
  <section class="base-panel"><h2>Unlock requirements</h2><p class="base-help">Includes prerequisite technologies; each is counted once. ${profile?.progress?.technologies?'Compared with your imported technology records.':'No imported unlock records; showing the full requirements.'}</p><p>${points.normal} technology points · ${points.ancient} ancient technology points${learned.size?' still needed':''}</p><div class="base-table-scroll"><table><thead><tr><th>Technology</th><th>Level</th><th>Points</th><th>Status</th></tr></thead><tbody>${required.ids.map(id=>{const t=data.technologies[id];return `<tr><td><a href="#technology/${encodeURIComponent(id)}">${esc(t.name)}</a>${t.research?`<small> · research: ${esc(t.research)}</small>`:''}${t.boss?`<small> · boss: ${esc(t.boss)}</small>`:''}</td><td>${t.level}</td><td>${t.cost}${t.ancient?' ancient':''}</td><td>${learned.has(id.toLowerCase())?'Imported unlocked':'Required'}</td></tr>`;}).join('')||'<tr><td colspan="4">No linked technology for these parts.</td></tr>'}</tbody></table></div><h3>Schematics</h3>${bill.schematics.size?`<ul>${[...bill.schematics].map(id=>`<li>${itemLink(id)}</li>`).join('')}</ul>`:'<p class="base-help">No building schematic requirement recorded for the selected parts.</p>'}${unknownUnlocks.length?`<p class="base-alert">Unlock availability is unverified for ${unknownUnlocks.map(([id])=>esc(buildings.get(id).name)).join(', ')}; no technology or schematic link was recorded.</p>`:''}${required.unknown.length||required.cycles.length?'<p class="base-alert">Some prerequisite records could not be resolved; costs may be incomplete.</p>':''}<p class="base-help">Blueprint planning does not unlock parts in-game. Research, boss, base-only and indoor requirements still apply.</p><details class="base-help"><summary>Data coverage</summary><p>${data.buildings.length} catalog parts, including stations, storage, decorations and building sets. ${data.buildings.filter(b=>b.envelope).length} have extracted mesh envelopes; the remainder use editable estimates. Four additional uncataloged native rows lack established player availability and are excluded. Names use the independent Arkive catalog; costs, schematics, unlocks and mesh bounds are independently extracted from installed game files. <a href="#about">Sources</a>.</p></details></section>`;
 }
 function update(){try{localStorage.setItem(selectionKey,current);}catch{}q('#base-plans').innerHTML=plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');q('#base-plans').value=current;q('#base-name').value=plan().name;q('#base-notes').value=plan().notes;q('#base-undo').disabled=!undo.length;q('#base-redo').disabled=!redo.length;q('#base-part-count').textContent=`${visible().length} shown / ${plan().parts.length} parts`;const b=buildings.get(brush);q('#base-brush').textContent=`Selected part: ${b.name}. ${mode==='place'?'Tap the blueprint or Add at center to place it.':'Use Place to add more.'}`;q('#base-pieces').innerHTML=plan().parts.map((p,i)=>`<button data-select="${esc(p.id)}" aria-pressed="${selected===p.id}"><span>${i+1}. ${esc(buildings.get(p.building)?.name||p.building)}</span><small>Z ${number(p.z)} m</small></button>`).join('')||'<p>No parts placed yet.</p>';selection();bill();draw();}
 function chooseMode(m){mode=m;for(const b of q('#base-modes').querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',b.dataset.mode===m);update();}
 function place(pos){if(plan().parts.length>=2000){status('This blueprint has reached its 2,000-part limit.');return;}const p={id:crypto.randomUUID(),building:brush,x:snap(pos.x,step),y:snap(pos.y,step),z:snap(pos.z,step),rotation};saveMutation(()=>{plan().parts.push(p);selected=p.id;});}
 function actionPart(action){const p=plan().parts.find(x=>x.id===selected);if(!p)return;saveMutation(()=>{if(action==='turn')p.rotation=rotate(p.rotation+90);if(action==='delete'){plan().parts=plan().parts.filter(x=>x.id!==p.id);selected=null;}if(action==='reset')delete p.size;if(action==='duplicate'){const duplicate={...copy(p),id:crypto.randomUUID(),x:p.x+step,y:p.y+step};plan().parts.push(duplicate);selected=duplicate.id;}});}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.brush){brush=b.dataset.brush;chooseMode('place');library();if(matchMedia('(max-width:650px)').matches){q('.base-library').open=false;canvas.scrollIntoView({block:'center',behavior:'smooth'});}}if(b.dataset.view){view=b.dataset.view;for(const button of q('#base-views').querySelectorAll('button'))button.setAttribute('aria-pressed',button.dataset.view===view);fit();}if(b.dataset.mode)chooseMode(b.dataset.mode);if(b.dataset.select){selected=b.dataset.select;chooseMode('select');}if(b.id==='base-apply-position')applyFields(false);if(b.id==='base-apply-size')applyFields(true);if(b.id==='base-turn')actionPart('turn');if(b.id==='base-delete')actionPart('delete');if(b.id==='base-duplicate')actionPart('duplicate');if(b.id==='base-size-reset')actionPart('reset');},{signal});
 function applyFields(sizeOnly){const p=plan().parts.find(x=>x.id===selected);if(!p)return;const fields=[...q('#base-selection').querySelectorAll(sizeOnly?'[data-size-field]':'[data-part-field]')];if(fields.some(f=>!f.value||!f.checkValidity())){status('Enter valid positions, rotation or sizes before applying.');return;}const values=fields.map(f=>Number(f.value));saveMutation(()=>{if(sizeOnly)p.size=values;else ['x','y','z','rotation'].forEach((k,i)=>p[k]=values[i]);});}
 for(const selector of ['#base-search','#base-category','#base-group'])on(selector,selector==='#base-search'?'input':'change',library);
 on('#base-plans','change',e=>{current=e.target.value;selected=null;update();fit();});
 on('#base-name','input',e=>{const value=e.target.value.trim();if(!value){status('Give the blueprint a name.');return;}saveMutation(()=>plan().name=value);});on('#base-notes','input',e=>saveMutation(()=>plan().notes=e.target.value));
 on('#base-new','click',()=>saveMutation(()=>{const p=newBlueprint();plans.push(p);current=p.id;selected=null;camera={scale:24,x:0,y:0};}));
 on('#base-copy','click',()=>saveMutation(()=>{const p={...copy(plan()),id:crypto.randomUUID(),name:(plan().name+' copy').slice(0,100)};plans.push(p);current=p.id;selected=null;}));
 on('#base-remove','click',()=>saveMutation(()=>{plans=plans.filter(p=>p.id!==current);if(!plans.length)plans=[newBlueprint()];current=plans[0].id;selected=null;},'Base removed. Use Undo to restore it.'));
 on('#base-plane','input',e=>{if(!e.target.value||!e.target.checkValidity())return;plane=Number(e.target.value);update();});on('#base-step','change',e=>{step=Number(e.target.value);draw();});on('#base-rotation','change',e=>rotation=Number(e.target.value));on('#base-labels','change',e=>{labels=e.target.checked;draw();});on('#base-isolate','change',e=>{isolated=e.target.checked;update();});
 on('#base-add','click',()=>place(world([canvas.clientWidth/2,canvas.clientHeight/2])));on('#base-undo','click',()=>history(undo,redo));on('#base-redo','click',()=>history(redo,undo));on('#base-fit','click',fit);
 const zoom=(factor,point=[canvas.clientWidth/2,canvas.clientHeight/2])=>{const old=camera.scale;camera.scale=Math.max(2,Math.min(160,old*factor));const ratio=camera.scale/old;camera.x=(camera.x-point[0]+canvas.clientWidth/2)*ratio+point[0]-canvas.clientWidth/2;camera.y=(camera.y-point[1]+canvas.clientHeight/2)*ratio+point[1]-canvas.clientHeight/2;draw();};
 on('#base-zoom-in','click',()=>zoom(1.3));on('#base-zoom-out','click',()=>zoom(1/1.3));
 on('#base-export','click',()=>download('palwaypoint-blueprint.json',new Blob([JSON.stringify(exportBlueprint(plan()),null,2)],{type:'application/json'})));
 on('#base-image','click',()=>{draw();canvas.toBlob(blob=>{if(blob)download(`palwaypoint-${view}.png`,blob);},'image/png');});on('#base-print','click',()=>window.print());
 on('#base-import','change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1_000_000)throw Error('Choose a blueprint smaller than 1 MB.');const imported=parseBlueprint(await file.text());if(!root.isConnected)return;saveMutation(()=>{const beforeCount=plans.length;plans=mergeBlueprints(plans,[imported]);current=plans.length>beforeCount?plans.at(-1).id:imported.id;selected=null;},'Blueprint imported; existing designs were kept.');fit();}catch(error){status(error.message);}finally{e.target.value='';}});
 const point=e=>{const rect=canvas.getBoundingClientRect();return [e.clientX-rect.left,e.clientY-rect.top];};
 const pick=pos=>[...polygons].reverse().find(p=>insidePolygon(pos,p.poly))?.id;
 on('#base-canvas','pointerdown',e=>{if(e.button!==0)return;canvas.focus({preventScroll:true});const pos=point(e);canvas.setPointerCapture(e.pointerId);if(mode==='select'){selected=pick(pos)||null;selection();draw();}const part=plan().parts.find(p=>p.id===selected);drag={start:pos,last:pos,camera:{...camera},id:mode==='select'?selected:null,original:part?copy(part):null,moved:false};});
 on('#base-canvas','pointermove',e=>{const pos=point(e);hover=pos;if(!drag){draw();return;}const dx=pos[0]-drag.start[0],dy=pos[1]-drag.start[1];if(Math.hypot(dx,dy)>4)drag.moved=true;if(mode==='pan'){camera.x=drag.camera.x+dx;camera.y=drag.camera.y+dy;}else if(mode==='select'&&drag.id&&drag.moved){const p=plan().parts.find(p=>p.id===drag.id),start=world(drag.start,drag.original),now=world(pos,drag.original);for(const axis of ['x','y','z'])p[axis]=snap(drag.original[axis]+now[axis]-start[axis],step);}drag.last=pos;draw();});
 const finish=e=>{if(!drag)return;const d=drag;drag=null;if(mode==='place'&&!d.moved)place(world(point(e)));else if(mode==='select'&&d.id&&d.moved){const p=plan().parts.find(x=>x.id===d.id),next=copy(p);Object.assign(p,d.original);saveMutation(()=>Object.assign(p,next));}else update();};
 on('#base-canvas','pointerup',finish);on('#base-canvas','pointercancel',()=>{if(drag?.original)Object.assign(plan().parts.find(p=>p.id===drag.id),drag.original);drag=null;update();});on('#base-canvas','pointerleave',()=>{hover=null;draw();});
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.12:1/1.12,point(e));},{passive:false,signal});
 on('#base-canvas','keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?redo:undo,e.shiftKey?undo:redo);}else if(mode==='select'&&e.key.toLowerCase()==='r'){e.preventDefault();actionPart('turn');}else if(mode==='select'&&['Delete','Backspace'].includes(e.key)){e.preventDefault();actionPart('delete');}});
 const resize=new ResizeObserver(()=>draw());resize.observe(canvas);library();update();
 return {dispose:()=>{controller.abort();resize.disconnect();},refresh:()=>{const stored=readBlueprints(localStorage);latest=localStorage.getItem(baseStorageKey);{plans=stored.length?stored:[newBlueprint()];if(!plans.some(p=>p.id===current))current=plans[0].id;selected=null;undo=[];redo=[];update();status('Blueprints refreshed from another tab.');}}};
}
