import {newBlueprint,readBlueprints,writeBlueprints,parseBlueprint,exportBlueprint,mergeBlueprints,baseStorageKey} from './base-storage.js';
import {project,unproject,snap,rotate,defaultEnvelope,partEnvelope,meshFor,insidePolygon,constructionBill,rawBill,technologyRequirements} from './base-logic.js';
import {structuralSnap} from './base-snapping.js?v=base-2';
import {readProfile} from './player-tools/storage.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>Number(n.toFixed(2)).toLocaleString();
const copy=x=>structuredClone(x);
const groupNames={Barieer:'Gates & defensive walls',Clean:'Advanced structures',Deforest_Mining:'Logging & mining',EfficiencEnhancement:'Work improvements',FeedBox:'Feed boxes',FishingPond:'Fishing ponds',Interception:'Defenses',PalCaptureItem:'Sphere crafting',PalManagement:'Pal management',PalOther:'Pal facilities',PalTraining:'Training & breeding',Product_Repair:'Crafting & repair',Refine:'Furnaces',StorageFurniture:'Storage furniture',WallDecoration:'Wall decorations',WallHanging:'Wall lights',Milling_Crusher:'Mills & crushers',JapaneseStyle:'Japanese style'};
const groupName=id=>groupNames[id]||id.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ');
const categoryNames={Foundation:'Building parts',Product:'Crafting stations',Pal:'Pal care',Infrastructure:'Base facilities',Light:'Lighting',Food:'Farming & food',Defense:'Defenses'};
const categoryName=id=>categoryNames[id]||groupName(id);
const download=(name,blob)=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
let cached;
export async function renderBaseBuilder(content){
 const initialHash=location.hash;content.innerHTML='<p>Opening the blueprint editor…</p>';
 if(!cached){const r=await fetch('./base-data.json?v=base-1');if(!r.ok)throw Error('Building data could not load.');cached=await r.json();}
 if(location.hash!==initialHash)return;
 const visuals=await fetch('./base-visuals.json?v=base-2').then(r=>{if(!r.ok)throw Error('Building artwork could not load.');return r.json();});if(location.hash!==initialHash)return;
 const {createBaseScene}=await import('./base-scene.js?v=base-2');if(location.hash!==initialHash)return;
 const data=cached,buildings=new Map(data.buildings.map(x=>[x.id,x]));
 const itemData=await fetch('./wiki-data.json?v=recovery-2').then(r=>{if(!r.ok)throw Error('Item names could not load.');return r.json();});if(location.hash!==initialHash)return;
 const items=new Map(itemData.items.map(x=>[x.id,x]));
 let plans=readBlueprints(localStorage);if(!plans.length)plans=[newBlueprint()];
 const selectionKey='palwaypoint-blueprint-selection-v1';
 let current=localStorage.getItem(selectionKey);if(!plans.some(p=>p.id===current))current=plans[0].id;
 let selected=null,brush='Wooden_foundation',mode='place',view='isometric',plane=0,step=.5,rotation=0,isolated=false,structureSnap=true,undo=[],redo=[],drag=null;
 let latest=localStorage.getItem(baseStorageKey);
 const controller=new AbortController(),signal=controller.signal;
 const plan=()=>plans.find(p=>p.id===current);
 content.innerHTML=`<div class="base-builder">
 <div class="base-stage"><canvas id="base-canvas" class="base-canvas" tabindex="0" aria-label="Base blueprint. Tap to place a part, drag to pan, right drag or two-finger drag to rotate. Use Parts & materials for keyboard position editing."></canvas></div>
 <div class="base-top"><button id="base-catalog-toggle" aria-label="Building parts" aria-expanded="false">☰ Parts</button><label class="base-view-picker">View<select id="base-view"><option value="isometric">Isometric</option><option value="top">Top</option><option value="front">Front</option><option value="back">Back</option><option value="left">Left</option><option value="right">Right</option><option value="orbit">Free view</option></select></label><button id="base-details-toggle" aria-label="Parts &amp; materials" aria-expanded="false"><span class="base-desktop-text">Parts &amp; materials</span><span class="base-mobile-text">Lists</span></button></div>
 <aside class="base-library base-drawer" aria-label="Building parts"><div class="base-drawer-title"><a class="base-brand" href="./index.html"><svg viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="16" r="9"/><path d="M16 1v9m0 12v9M1 16h9m12 0h9"/><circle cx="16" cy="16" r="2"/></svg>PalWaypoint</a><button id="base-catalog-close" aria-label="Close building parts">×</button></div>
 <div class="base-catalog-tools"><label>Find a part<input id="base-search" type="search" placeholder="Foundation, chest, station…"></label><div class="base-filter-row"><label>Category<select id="base-category"><option value="">All categories</option>${[...new Set(data.buildings.map(b=>b.category))].map(c=>`<option value="${esc(c)}">${esc(categoryName(c))}</option>`).join('')}</select></label><label>Building set<select id="base-group"><option value="">All sets</option>${[...new Set(data.buildings.map(b=>b.group))].sort().map(c=>`<option value="${esc(c)}">${esc(groupName(c))}</option>`).join('')}</select></label></div></div><p id="base-catalog-count"></p><div id="base-library" class="base-part-list"></div><a class="base-return" href="./index.html">Return to map</a></aside>
 <aside class="base-details base-drawer" aria-label="Blueprint details"><div class="base-drawer-title"><strong>Blueprint</strong><button id="base-details-close" aria-label="Close blueprint details">×</button></div><div class="base-detail-tabs" role="group" aria-label="Blueprint panels"><button data-panel="plan" aria-pressed="true">Design</button><button data-panel="pieces" aria-pressed="false">Placed parts</button><button data-panel="materials" aria-pressed="false">Materials</button></div><div class="base-detail-scroll">
 <section data-panel-content="plan"><div class="base-manager"><label>Saved blueprint<select id="base-plans"></select></label><label>Blueprint name<input id="base-name" maxlength="100"></label><div class="base-actions"><button id="base-new">New base</button><button id="base-copy">Copy base</button><button id="base-remove" class="base-danger">Delete base</button></div></div><label class="base-notes">Design notes<textarea id="base-notes" rows="3" maxlength="4000"></textarea></label><label class="base-toggle"><input type="checkbox" id="base-isolate">Only placement height</label><div class="base-actions"><button id="base-export">Export blueprint</button><button id="base-image">Export view PNG</button><button id="base-print">Print</button></div><label class="base-import base-help">Import blueprint JSON<input type="file" accept=".json,application/json" id="base-import"></label><p class="base-help">Plans stay on this device. <a href="#backup">Back up &amp; restore progress</a></p><details class="base-help"><summary>Controls &amp; accuracy</summary><p>Tap to place; drag to pan. Right drag rotates on desktop. Two-finger drag rotates on touch screens; pinch zooms. Select a part to move it, or edit its coordinates in Placed parts. R rotates 90°; Delete removes the selected part; Ctrl/Cmd+Z undoes.</p><p>Native game thumbnails, meshes and color/normal textures are used where recovered. Unreal shaders, animations and effects are approximated. Outlined envelopes identify models that are unavailable or loading.</p><p>Structure snapping reconstructs square foundation edges, wall connections and floors above walls using native placement families and measured dimensions. Triangles, sloped roofs, stairs and freestanding objects use the grid. Collision, structural support, terrain and Pal pathfinding are not validated; check your design in-game. Custom-sized targets do not offer structure connections. Z is the native pivot; foundations extend below it.</p><p><a href="#about">Sources &amp; credits</a> · <a href="#guide">Guide</a></p></details></section>
 <section data-panel-content="pieces" hidden><div id="base-selection" class="base-selection"></div><h3>Placed parts</h3><div id="base-pieces" class="base-piece-list"></div></section><section data-panel-content="materials" hidden><div id="base-bill" class="base-bill"></div></section></div></aside>
 <div class="base-history"><button id="base-undo" aria-label="Undo" disabled>Undo</button><button id="base-redo" aria-label="Redo" disabled>Redo</button></div><div class="base-zoom"><button id="base-zoom-in" aria-label="Zoom in">+</button><button id="base-fit" aria-label="Fit design">Fit</button><button id="base-zoom-out" aria-label="Zoom out">−</button></div>
 <div class="base-bottom"><div class="base-mode-row" id="base-modes"><button data-mode="place" aria-pressed="true">Place</button><button data-mode="select" aria-label="Select / move" aria-pressed="false">Move</button><button id="base-rotate-brush" aria-label="Rotate 90 degrees">Rotate</button><button id="base-add" aria-label="Add at center">+ Center</button></div><div class="base-place-controls"><label class="base-toggle"><input type="checkbox" id="base-structure-snap" checked>Structure snap</label><label>Grid<select id="base-step"><option value=".25">0.25 m</option><option value=".5" selected>0.5 m</option><option value="1">1 m</option><option value="2">2 m</option><option value="4">4 m</option></select></label><label>Z (m)<input id="base-plane" type="number" value="0" min="-500" max="500" step=".5"></label><label>Rotation<select id="base-rotation">${[0,45,90,135,180,225,270,315].map(n=>`<option value="${n}">${n}°</option>`).join('')}</select></label></div><p id="base-brush" class="base-editor-status"></p></div><div class="base-readout"><span id="base-part-count"></span><span id="base-view-label"></span><p id="base-status" role="status"></p></div></div>`;
 document.body.classList.add('base-fullscreen');
 const root=content.querySelector('.base-builder'),q=s=>root.querySelector(s),canvas=q('#base-canvas');
 const status=s=>{q('#base-status').textContent=s;};
 let scene;try{scene=createBaseScene(canvas,buildings,visuals,status);}catch(e){document.body.classList.remove('base-fullscreen');content.innerHTML='<p>The 3D editor could not start. Enable WebGL in your browser, or use another supported device. Saved blueprints are retained.</p>';throw Error('The 3D editor needs WebGL enabled in your browser. '+e.message);}
 const on=(s,event,handler)=>q(s).addEventListener(event,handler,{signal});
 const itemLink=id=>`<a href="#item/${encodeURIComponent(id)}">${esc(items.get(id)?.name||id)}</a>`;
 const visible=()=>plan().parts.filter(p=>!isolated||Math.abs(p.z-plane)<.001);
 function saveMutation(fn,message='Blueprint saved on this browser.'){
  const before=copy(plans),oldCurrent=current;
  try{if(localStorage.getItem(baseStorageKey)!==latest)throw Error('Blueprints changed in another tab. Reopen this page before editing.');fn();plans=writeBlueprints(localStorage,plans);latest=localStorage.getItem(baseStorageKey);undo.push({plans:before,current:oldCurrent});if(undo.length>60)undo.shift();redo=[];update();status(message);}
  catch(e){plans=before;current=oldCurrent;update();status(e.message);}
 }
 function history(from,to){if(!from.length)return;const state=from.at(-1),previous=copy(plans),old=current;try{if(localStorage.getItem(baseStorageKey)!==latest)throw Error('Blueprints changed in another tab. Reopen this page.');writeBlueprints(localStorage,state.plans);latest=localStorage.getItem(baseStorageKey);from.pop();to.push({plans:previous,current:old});plans=copy(state.plans);current=state.current;if(!plan().parts.some(p=>p.id===selected))selected=null;update();status('Blueprint saved.');}catch(e){status(e.message);}}
 function library(){const query=q('#base-search').value.trim().toLowerCase(),category=q('#base-category').value,group=q('#base-group').value;const found=[...data.buildings].sort((a,b)=>(a.category==='Foundation'?0:1)-(b.category==='Foundation'?0:1)).filter(b=>(!query||`${b.name} ${b.id}`.toLowerCase().includes(query))&&(!category||b.category===category)&&(!group||b.group===group));q('#base-catalog-count').textContent=`${found.length} / ${data.buildings.length} parts`;q('#base-library').innerHTML=found.map(b=>`<button data-brush="${esc(b.id)}" aria-pressed="${brush===b.id}">${visuals.buildings[b.id]?.icon?`<img src="./${esc(visuals.buildings[b.id].icon)}" alt="" loading="lazy" width="52" height="52">`:'<span class="base-part-symbol" aria-hidden="true"></span>'}<span><strong>${esc(b.name)}</strong><small>${esc(groupName(b.group))}${b.schematic?' · schematic':''}${!b.envelope?' · estimated size':''}</small></span></button>`).join('')||'<p>No matching parts.</p>';}
 function world(point){return scene.world(point,plane);}
 function draw(){scene.setPlane(plane);scene.update(visible(),selected);q('#base-view-label').textContent=`${view} · Z ${plane} m`;}
 function fit(){scene.fit();}
 function panel(name){for(const s of root.querySelectorAll('[data-panel-content]'))s.hidden=s.dataset.panelContent!==name;for(const b of root.querySelectorAll('[data-panel]'))b.setAttribute('aria-pressed',b.dataset.panel===name);}
 function drawer(name,open){root.classList.toggle(name+'-open',open);q(name==='catalog'?'#base-catalog-toggle':'#base-details-toggle').setAttribute('aria-expanded',open);}
 function selection(){const p=plan().parts.find(x=>x.id===selected);if(!p){q('#base-selection').innerHTML='<p class="base-help">Select a placed part to edit its position, rotation and size.</p>';return;}const b=buildings.get(p.building),e=partEnvelope(p,b),size=e.max.map((n,i)=>n-e.min[i]);q('#base-selection').innerHTML=`<h3>${esc(b?.name||p.building)}</h3><p class="base-help">${p.size?'Custom size':!b?.envelope?'Estimated size':b.envelope.quality==='partial-mesh-envelope'?'Partial mesh envelope':'Game mesh envelope'} · ${visuals.buildings[p.building]?.parts.length?'native game model':'estimated visual'}</p><div class="base-edit-fields">${['x','y','z','rotation'].map(k=>`<label>${k==='rotation'?'Rotation (°)':k.toUpperCase()+' (m)'}<input data-part-field="${k}" type="number" min="${k==='rotation'?0:-500}" max="${k==='rotation'?359.99:500}" step="any" value="${p[k]}"></label>`).join('')}${['Width (m)','Depth (m)','Height (m)'].map((k,i)=>`<label>${k}<input data-size-field="${i}" type="number" min=".01" max="100" step="any" value="${+size[i].toFixed(4)}"></label>`).join('')}</div><div class="base-actions"><button id="base-apply-position">Apply position</button><button id="base-apply-size">Apply size</button><button id="base-turn">Rotate 90°</button><button id="base-duplicate">Duplicate part</button><button id="base-size-reset">Reset size</button><button id="base-delete" class="base-danger">Remove part</button></div>${b?.description?`<p class="base-help">${esc(b.description)}</p>`:''}`;}
 function bill(){
  const bill=constructionBill(plan(),data),raw=rawBill(bill.materials,data.itemRecipes),required=technologyRequirements(bill.techs,data.technologies);let profile=null;try{profile=readProfile(localStorage);}catch{}
  const learned=new Set((profile?.progress?.technologies||[]).map(x=>x.toLowerCase())),owned=new Map();for(const stack of profile?.inventory||[])owned.set(stack.id,(owned.get(stack.id)||0)+stack.count);
  const mats=(map,compare=false)=>`<div class="base-table-scroll"><table><thead><tr><th>Material</th><th>Required</th>${compare?'<th>Carried</th><th>Missing</th>':''}</tr></thead><tbody>${[...map].sort((a,b)=>(items.get(a[0])?.name||a[0]).localeCompare(items.get(b[0])?.name||b[0])).map(([id,n])=>`<tr><td>${itemLink(id)}</td><td>${number(n)}</td>${compare?`<td>${number(owned.get(id)||0)}</td><td>${number(Math.max(0,n-(owned.get(id)||0)))}</td>`:''}</tr>`).join('')||'<tr><td colspan="4">Add a building part to start your materials list.</td></tr>'}</tbody></table></div>`;
  const compare=profile?.source==='local-world'&&Array.isArray(profile.inventory);
  const limits=[...bill.counts].filter(([id,n])=>buildings.get(id).limits.maxPerBase>0&&n>buildings.get(id).limits.maxPerBase);
  const unknownUnlocks=[...bill.counts].filter(([id])=>!buildings.get(id).technologies.length&&!buildings.get(id).schematic);
  const newTech=required.ids.filter(id=>!learned.has(id.toLowerCase())),points=newTech.reduce((r,id)=>{const t=data.technologies[id];r[t.ancient?'ancient':'normal']+=t.cost;return r;},{normal:0,ancient:0});
  q('#base-bill').innerHTML=`<section class="base-panel"><h2>Construction shopping list</h2><p class="base-help">${bill.counts.size} kinds of building · ${plan().parts.length} placed parts. Recipes are read from the installed game tables.</p>${mats(bill.materials,compare)}${compare?'<p class="base-help">Carried items are from your last local-world import. Base storage and already-built parts are not counted. Import a fresh save to update these amounts.</p>':'<p class="base-help">Import your own local world to compare with carried inventory. Server character files do not include it.</p>'}<details class="base-help"><summary>Raw materials if crafting everything</summary><p>Expands the recorded recipes, including intermediate materials. Each required batch is rounded up. This is an alternative list; do not add it to the construction list. Loot, purchases, alternate recipes and production settings can change what you need.</p>${mats(raw.materials)}${raw.issues.length?`<p class="base-alert">Recipe loops could not be expanded: ${raw.issues.map(itemLink).join(', ')}.</p>`:''}</details><h3>Building counts</h3><div class="base-table-scroll"><table><tbody>${[...bill.counts].map(([id,n])=>`<tr><td>${esc(buildings.get(id).name)}</td><td>×${n}</td></tr>`).join('')}</tbody></table></div>${limits.length?`<p class="base-alert">Recorded base limits exceeded: ${limits.map(([id])=>`${esc(buildings.get(id).name)} (max ${buildings.get(id).limits.maxPerBase})`).join(', ')}.</p>`:''}${bill.unknown.length?`<p class="base-alert">No recipe found for ${bill.unknown.map(esc).join(', ')}. These imported parts are retained but excluded from costs.</p>`:''}</section>
  <section class="base-panel"><h2>Unlock requirements</h2><p class="base-help">Includes prerequisite technologies; each is counted once. ${profile?.progress?.technologies?'Compared with your imported technology records.':'No imported unlock records; showing the full requirements.'}</p><p>${points.normal} technology points · ${points.ancient} ancient technology points${learned.size?' still needed':''}</p><div class="base-table-scroll"><table><thead><tr><th>Technology</th><th>Level</th><th>Points</th><th>Status</th></tr></thead><tbody>${required.ids.map(id=>{const t=data.technologies[id];return `<tr><td><a href="#technology/${encodeURIComponent(id)}">${esc(t.name)}</a>${t.research?`<small> · research: ${esc(t.research)}</small>`:''}${t.boss?`<small> · boss: ${esc(t.boss)}</small>`:''}</td><td>${t.level}</td><td>${t.cost}${t.ancient?' ancient':''}</td><td>${learned.has(id.toLowerCase())?'Imported unlocked':'Required'}</td></tr>`;}).join('')||'<tr><td colspan="4">No linked technology for these parts.</td></tr>'}</tbody></table></div><h3>Schematics</h3>${bill.schematics.size?`<ul>${[...bill.schematics].map(id=>`<li>${itemLink(id)}</li>`).join('')}</ul>`:'<p class="base-help">No building schematic requirement recorded for the selected parts.</p>'}${unknownUnlocks.length?`<p class="base-alert">Unlock availability is unverified for ${unknownUnlocks.map(([id])=>esc(buildings.get(id).name)).join(', ')}; no technology or schematic link was recorded.</p>`:''}${required.unknown.length||required.cycles.length?'<p class="base-alert">Some prerequisite records could not be resolved; costs may be incomplete.</p>':''}<p class="base-help">Blueprint planning does not unlock parts in-game. Research, boss, base-only and indoor requirements still apply.</p><details class="base-help"><summary>Data coverage</summary><p>${data.buildings.length} catalog parts, including stations, storage, decorations and building sets. ${data.buildings.filter(b=>b.envelope).length} have extracted mesh envelopes; the remainder use editable estimates. Four additional uncataloged native rows lack established player availability and are excluded. Names use the independent Arkive catalog; costs, schematics, unlocks and mesh bounds are independently extracted from installed game files. <a href="#about">Sources</a>.</p></details></section>`;
 }
 function update(){try{localStorage.setItem(selectionKey,current);}catch{}q('#base-plans').innerHTML=plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');q('#base-plans').value=current;q('#base-name').value=plan().name;q('#base-notes').value=plan().notes;q('#base-undo').disabled=!undo.length;q('#base-redo').disabled=!redo.length;q('#base-part-count').textContent=`${visible().length} shown / ${plan().parts.length} parts`;const b=buildings.get(brush);q('#base-brush').textContent=`Selected part: ${b.name}. ${mode==='place'?'':' · Select / move'}`;q('#base-pieces').innerHTML=plan().parts.map((p,i)=>`<button data-select="${esc(p.id)}" aria-pressed="${selected===p.id}"><span>${i+1}. ${esc(buildings.get(p.building)?.name||p.building)}</span><small>Z ${number(p.z)} m</small></button>`).join('')||'<p>No parts placed yet.</p>';selection();bill();draw();}
 function chooseMode(m){mode=m;scene.preview(null);for(const b of q('#base-modes').querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',b.dataset.mode===m);update();}
 function place(pos){if(plan().parts.length>=2000){status('This blueprint has reached its 2,000-part limit.');return;}const next=structuralSnap(pos,rotation,brush,plan().parts,buildings,visuals,step,structureSnap);const p={id:crypto.randomUUID(),building:brush,...Object.fromEntries(['x','y','z','rotation'].map(k=>[k,next[k]]))};if(plan().parts.some(x=>x.building===p.building&&['x','y','z','rotation'].every(k=>Math.abs(x[k]-p[k])<.001))){status('That part is already at this connection.');return;}saveMutation(()=>{plan().parts.push(p);selected=p.id;},next.snapped?'Placed at a reconstructed structure connection.':'Placed on the grid.');}
 function actionPart(action){const p=plan().parts.find(x=>x.id===selected);if(!p)return;saveMutation(()=>{if(action==='turn')p.rotation=rotate(p.rotation+90);if(action==='delete'){plan().parts=plan().parts.filter(x=>x.id!==p.id);selected=null;}if(action==='reset')delete p.size;if(action==='duplicate'){const duplicate={...copy(p),id:crypto.randomUUID(),x:p.x+step,y:p.y+step};plan().parts.push(duplicate);selected=duplicate.id;}});}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.brush){brush=b.dataset.brush;chooseMode('place');library();if(matchMedia('(max-width:650px)').matches){drawer('catalog',false);}}if(b.dataset.panel)panel(b.dataset.panel);if(b.dataset.mode)chooseMode(b.dataset.mode);if(b.dataset.select){selected=b.dataset.select;chooseMode('select');panel('pieces');}if(b.id==='base-apply-position')applyFields(false);if(b.id==='base-apply-size')applyFields(true);if(b.id==='base-turn')actionPart('turn');if(b.id==='base-delete')actionPart('delete');if(b.id==='base-duplicate')actionPart('duplicate');if(b.id==='base-size-reset')actionPart('reset');},{signal});
 function applyFields(sizeOnly){const p=plan().parts.find(x=>x.id===selected);if(!p)return;const fields=[...q('#base-selection').querySelectorAll(sizeOnly?'[data-size-field]':'[data-part-field]')];if(fields.some(f=>!f.value||!f.checkValidity())){status('Enter valid positions, rotation or sizes before applying.');return;}const values=fields.map(f=>Number(f.value));saveMutation(()=>{if(sizeOnly)p.size=values;else ['x','y','z','rotation'].forEach((k,i)=>p[k]=values[i]);});}
 for(const selector of ['#base-search','#base-category','#base-group'])on(selector,selector==='#base-search'?'input':'change',library);
 on('#base-plans','change',e=>{current=e.target.value;selected=null;update();fit();});
 on('#base-name','input',e=>{const value=e.target.value.trim();if(!value){status('Give the blueprint a name.');return;}saveMutation(()=>plan().name=value);});on('#base-notes','input',e=>saveMutation(()=>plan().notes=e.target.value));
 on('#base-new','click',()=>{saveMutation(()=>{const p=newBlueprint();plans.push(p);current=p.id;selected=null;});fit();});
 on('#base-copy','click',()=>saveMutation(()=>{const p={...copy(plan()),id:crypto.randomUUID(),name:(plan().name+' copy').slice(0,100)};plans.push(p);current=p.id;selected=null;}));
 on('#base-remove','click',()=>saveMutation(()=>{plans=plans.filter(p=>p.id!==current);if(!plans.length)plans=[newBlueprint()];current=plans[0].id;selected=null;},'Base removed. Use Undo to restore it.'));
 on('#base-plane','input',e=>{if(!e.target.value||!e.target.checkValidity())return;plane=Number(e.target.value);update();});on('#base-step','change',e=>{step=Number(e.target.value);draw();});on('#base-rotation','change',e=>rotation=Number(e.target.value));on('#base-isolate','change',e=>{isolated=e.target.checked;update();});
 on('#base-add','click',()=>place(world([canvas.clientWidth/2,canvas.clientHeight/2])));on('#base-undo','click',()=>history(undo,redo));on('#base-redo','click',()=>history(redo,undo));on('#base-fit','click',fit);
 const zoom=factor=>scene.zoom(factor);
 on('#base-zoom-in','click',()=>zoom(1.3));on('#base-zoom-out','click',()=>zoom(1/1.3));
 on('#base-view','change',e=>{view=e.target.value;if(view!=='orbit')scene.setView(view);draw();});
 on('#base-structure-snap','change',e=>structureSnap=e.target.checked);
 on('#base-catalog-toggle','click',()=>drawer('catalog',!root.classList.contains('catalog-open')));on('#base-catalog-close','click',()=>drawer('catalog',false));
 on('#base-details-toggle','click',()=>{drawer('details',!root.classList.contains('details-open'));if(matchMedia('(max-width:650px)').matches)drawer('catalog',false);});on('#base-details-close','click',()=>drawer('details',false));
 function turn(){if(mode==='select'&&selected)actionPart('turn');else{rotation=rotate(rotation+90);q('#base-rotation').value=rotation;status(`Next part rotated to ${rotation}°.`);}}
 on('#base-rotate-brush','click',turn);
 on('#base-export','click',()=>download('palwaypoint-blueprint.json',new Blob([JSON.stringify(exportBlueprint(plan()),null,2)],{type:'application/json'})));
 on('#base-image','click',()=>{draw();canvas.toBlob(blob=>{if(blob)download(`palwaypoint-${view}.png`,blob);},'image/png');});on('#base-print','click',()=>window.print());
 on('#base-import','change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1_000_000)throw Error('Choose a blueprint smaller than 1 MB.');const imported=parseBlueprint(await file.text());if(!root.isConnected)return;saveMutation(()=>{const beforeCount=plans.length;plans=mergeBlueprints(plans,[imported]);current=plans.length>beforeCount?plans.at(-1).id:imported.id;selected=null;},'Blueprint imported; existing designs were kept.');fit();}catch(error){status(error.message);}finally{e.target.value='';}});
 const point=e=>{const rect=canvas.getBoundingClientRect();return [e.clientX-rect.left,e.clientY-rect.top];};
 const pointers=new Map();let gesture=null;
 const distance=()=>{const a=[...pointers.values()];return Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);};
 const center=()=>{const a=[...pointers.values()];return[(a[0][0]+a[1][0])/2,(a[0][1]+a[1][1])/2];};
 function cancelMove(){if(drag?.original){const p=plan().parts.find(p=>p.id===drag.id);if(p)Object.assign(p,drag.original);}drag=null;}
 on('#base-canvas','pointerdown',e=>{if(e.button!==0&&e.button!==2)return;scene.preview(null);canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);const pos=point(e);pointers.set(e.pointerId,pos);if(pointers.size>=2){cancelMove();gesture={center:center(),distance:distance()};draw();return;}if(mode==='select'&&e.button===0){selected=scene.pick(pos);selection();draw();}const part=plan().parts.find(p=>p.id===selected);drag={pointer:e.pointerId,start:pos,last:pos,right:e.button===2,id:mode==='select'&&e.button===0?selected:null,original:part?copy(part):null,moved:false};});
 on('#base-canvas','pointermove',e=>{const pos=point(e);if(!pointers.has(e.pointerId)){if(mode==='place'){const n=structuralSnap(world(pos),rotation,brush,plan().parts,buildings,visuals,step,structureSnap);scene.preview({building:brush,...n});}return;}pointers.set(e.pointerId,pos);if(pointers.size>=2){const c=center(),d=distance();if(gesture){scene.orbit(c[0]-gesture.center[0],c[1]-gesture.center[1]);if(gesture.distance>0)zoom(d/gesture.distance);view='orbit';q('#base-view').value='orbit';}gesture={center:c,distance:d};return;}if(gesture||!drag)return;const dx=pos[0]-drag.last[0],dy=pos[1]-drag.last[1];if(Math.hypot(pos[0]-drag.start[0],pos[1]-drag.start[1])>5)drag.moved=true;if(drag.right){scene.orbit(dx,dy);view='orbit';q('#base-view').value='orbit';}else if(drag.id&&drag.moved){const p=plan().parts.find(p=>p.id===drag.id),start=world(drag.start),now=world(pos),raw=Object.fromEntries(['x','y','z'].map(k=>[k,drag.original[k]+now[k]-start[k]])),next=structuralSnap(raw,p.rotation,p.building,plan().parts,buildings,visuals,step,structureSnap,p.id);for(const k of ['x','y','z','rotation'])p[k]=next[k];draw();}else if(drag.moved)scene.pan(dx,dy);drag.last=pos;});
 on('#base-canvas','pointerup',e=>{pointers.delete(e.pointerId);if(gesture){cancelMove();if(!pointers.size)gesture=null;update();return;}const d=drag;drag=null;if(!d)return;if(d.id&&d.moved){const p=plan().parts.find(p=>p.id===d.id),next=copy(p);Object.assign(p,d.original);saveMutation(()=>Object.assign(p,next));}else if(!d.right&&!d.moved&&mode==='place')place(world(point(e)));else update();});
 on('#base-canvas','pointercancel',e=>{pointers.delete(e.pointerId);cancelMove();if(!pointers.size)gesture=null;update();});on('#base-canvas','contextmenu',e=>e.preventDefault());on('#base-canvas','pointerleave',()=>scene.preview(null));
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.12:1/1.12);},{passive:false,signal});
 on('#base-canvas','keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?redo:undo,e.shiftKey?undo:redo);}else if(e.key.toLowerCase()==='r'){e.preventDefault();turn();}else if(e.key==='Escape'){drawer('catalog',false);drawer('details',false);}else if(mode==='select'&&['Delete','Backspace'].includes(e.key)){e.preventDefault();actionPart('delete');}});
 library();update();if(!matchMedia('(max-width:650px)').matches)drawer('catalog',true);
 return {dispose:()=>{controller.abort();scene.dispose();document.body.classList.remove('base-fullscreen');},refresh:()=>{const stored=readBlueprints(localStorage);latest=localStorage.getItem(baseStorageKey);{plans=stored.length?stored:[newBlueprint()];if(!plans.some(p=>p.id===current))current=plans[0].id;selected=null;undo=[];redo=[];update();status('Blueprints refreshed from another tab.');}}};
}
